slug: "prodor-led-bazenski-reflektor-rgb-35W-mlaznica"
title: "Reflektor LED 35W RGB za prodor 2\""
price: 320
description: |
  Slim 35W RGB - Epoxy
  Full RGB sa daljinskim RF do 30m
  Dimabilne - podešavanje jačine
  
  -Montaza na prodor 2" za liner bazene
  -Montaza za poliesterske bazene sa pripadajućim dihtunzima i spojkama
  -Montaza na betonske bazene/keramiku
  
  
  SMD 2835 čipovi Class A1
  Napon 12V AC
  Epoxy transparenta smola za zastitu IP68 unutrasnjih komponenti
  
  Garancija 2 godine
  Zastupnik za Poolux Shenzhen
category: "bazenska-rasvjeta"
updatedAt: "2026-01-25T18:59:53.228Z"
images:
  - url: "https://res.cloudinary.com/di4fsjiqk/image/upload/v1769367585/img_1766693900_70d2cf2a665e_8496564d1b.jpg"
    alt: "Reflektor LED bazenski 35W rgb epoxy zastita ip68 sa daljinskim upravljacem i montazom na prodor ili mlaznicu"
  - url: "https://res.cloudinary.com/di4fsjiqk/image/upload/v1769367354/img_1766693900_7af0946a84c7_ccd8e36b7d.jpg"
    alt: "Reflektor LED 35W RGB za prodor 2\""
  - url: "https://res.cloudinary.com/di4fsjiqk/image/upload/v1769367354/img_1766693899_0ed389e5be5b_43c89bd45a.jpg"
    alt: "Reflektor LED 35W RGB za prodor 2\""
  - url: "https://res.cloudinary.com/di4fsjiqk/image/upload/v1769367354/img_1766693900_8da8a23dafac_e5722f406f.jpg"
    alt: "Reflektor LED 35W RGB za prodor 2\""
  - url: "https://res.cloudinary.com/di4fsjiqk/image/upload/v1769367355/img_1766693900_655b5c7d959e_0eb4b1e6e6.jpg"
    alt: "Reflektor LED 35W RGB za prodor 2\""
  - url: "https://res.cloudinary.com/di4fsjiqk/image/upload/v1769367355/img_1766693899_b957d50e14e0_0a14f250a6.jpg"
    alt: "Reflektor LED 35W RGB za prodor 2\""
  - url: "https://res.cloudinary.com/di4fsjiqk/image/upload/v1769367355/img_1766693900_dc45600ad020_d19730a1ef.jpg"
    alt: "Reflektor LED 35W RGB za prodor 2\""
