import { Outfit } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import Footer from "./_components/Footer";
import { Toaster } from "@/components/ui/sonner";
import { CartProvider } from './_components/CartContext'; // Adjust the path accordingly
import MenuItems from "./_components/MenuItems";
import ScrollToTop from "./_components/ScrolltoTop";

const inter = Outfit({ subsets: ['latin'] });

export const metadata = {
  title: "Led Tehnika",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CartProvider>
          <Header />
          <div className="pt-24">
            <ScrollToTop />

            {children}
          </div>
          <Toaster />
          <MenuItems />
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}
