import { Outfit } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import Footer from "./_components/Footer";
import { Toaster } from "@/components/ui/sonner";
import { CartProvider } from './_components/CartContext'; // Adjust the path accordingly
import MenuItems from "./_components/MenuItems";
import ScrollToTop from "./_components/ScrolltoTop";
import Head from "next/head";

const inter = Outfit({ subsets: ['latin'] });

export const metadata = {
  title: "Led Tehnika",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",  // ovo će automatski staviti link u head
  },
};



export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <Head>
        <title>Led Tehnika</title>
        <meta name="description" content="Ekskluzivni uvoznik bazenske i LED rasvjete, motora za kapije,kalolifera i još mnogo toga." />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body className={inter.className}>
        <CartProvider>
          <Header />
          <div className="pt-24">
            <ScrollToTop />

            {children}
          </div>
          <Toaster duration={1000} richColors  />
          <MenuItems />
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}
